(function(g){var window=this;'use strict';var AXa=function(a,b){return g.Ye(a,b)},BXa=function(a,b){b=b instanceof g.Yf?b:g.hg(b,/^data:image\//i.test(b));
a.src=g.cg(b)},Y6=function(a){g.ml(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ta()).toString(36));
return a},Z6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.rl(a.u,b,c)},CXa=function(a){if(a===g.Hp)throw Error("ES6 Iteration protocol does NOT adjust control flow when StopIteration is thrown from callback helper functions. If your code relies on this behavior, consider throwing a different error and catching it to terminate iteration.");
throw a;},DXa=function(a){if(a instanceof g.Fp)return a;
if("function"==typeof a.Ng)return a.Ng(!1);if(g.Ma(a)){var b=0,c=new g.Fp;c.next=function(){for(;;){if(b>=a.length)return g.i2;if(b in a)return g.Gp(a[b++]);b++}};
var d=c.next;c.Lj=function(){return g.Ip(d.call(c))};
return c}throw Error("Not implemented");},EXa=function(a,b,c){if(g.Ma(a))try{g.sc(a,b,c)}catch(e){CXa(e)}else for(a=DXa(a);;){var d=void 0;
try{d=a.Lj()}catch(e){if(e===g.Hp)break;throw e;}try{b.call(c,d,void 0,a)}catch(e){CXa(e)}}},FXa=function(a,b){var c=[];
EXa(b,function(d){try{var e=g.hs.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.vga(e)&&c.push(d)},a);
return c},GXa=function(a,b){FXa(a,b).forEach(function(c){g.hs.prototype.remove.call(this,c)},a)},HXa=function(a){if(a.ma){if(a.ma.locationOverrideToken)return{locationOverrideToken:a.ma.locationOverrideToken};
if(null!=a.ma.latitudeE7&&null!=a.ma.longitudeE7)return{latitudeE7:a.ma.latitudeE7,longitudeE7:a.ma.longitudeE7}}return null},IXa=function(a,b){g.$b(a,b)||a.push(b)},$6=function(a){var b=0,c;
for(c in a)b++;return b},JXa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},a7=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return JXa(a)},KXa=function(a,b,c,d){var e=new g.el(null,void 0);
a&&g.fl(e,a);b&&g.gl(e,b);c&&g.hl(e,c);d&&(e.K=d);return e},b7=function(a,b){g.nv[a]=!0;
var c=g.lv();c&&c.publish.apply(c,arguments);g.nv[a]=!1},c7=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Qr;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",LXa(this,a.capabilities||""),MXa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},LXa=function(a,b){a.capabilities.clear();
g.aq(b.split(","),g.Sa(AXa,NXa)).forEach(function(c){a.capabilities.add(c)})},MXa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},d7=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},e7=function(a,b){return!!b&&(a.id==b||a.uuid==b)},OXa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},PXa=function(a){return new d7(a)},QXa=function(a){return Array.isArray(a)?g.co(a,PXa):[]},f7=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},g7=function(a){return Array.isArray(a)?"["+g.co(a,f7).join(",")+"]":"null"},h7=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},RXa=function(a){return g.co(a,function(b){return{key:b.id,
name:b.name}})},i7=function(a,b){return g.Wb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},j7=function(a,b){return g.Wb(a,function(c){return e7(c,b)})},SXa=function(){var a=(0,g.yy)();
a&&GXa(a,a.i.Ng(!0))},k7=function(){var a=g.By("yt-remote-connected-devices")||[];
g.oc(a);return a},TXa=function(a){if(g.ac(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.co(a,function(d,e){return 0==e?d:d.substring(c.length)})},UXa=function(a){g.Ay("yt-remote-connected-devices",a,86400)},m7=function(){if(l7)return l7;
var a=g.By("yt-remote-device-id");a||(a=h7(),g.Ay("yt-remote-device-id",a,31536E3));for(var b=k7(),c=1,d=a;g.$b(b,d);)c++,d=a+"#"+c;return l7=d},n7=function(){var a=k7(),b=m7();
g.$b(a,b);g.Dy()&&g.qc(a,b);a=TXa(a);if(g.ac(a))try{g.Vja("remote_sid")}catch(c){}else try{g.ku("remote_sid",a.join(","),-1)}catch(c){}},VXa=function(){return g.By("yt-remote-session-browser-channel")},WXa=function(){return g.By("yt-remote-local-screens")||[]},XXa=function(){g.Ay("yt-remote-lounge-token-expiration",!0,86400)},YXa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.co(WXa(),function(d){return d.loungeToken}),c=g.co(a,function(d){return d.loungeToken});
g.eo(c,function(d){return!g.$b(b,d)})&&XXa();
g.Ay("yt-remote-local-screens",a,31536E3)},ZXa=function(a,b){g.Ay("yt-remote-session-browser-channel",a);
g.Ay("yt-remote-session-screen-id",b);a=k7();b=m7();g.$b(a,b)||a.push(b);UXa(a);n7()},o7=function(a){a||(g.Cy("yt-remote-session-screen-id"),g.Cy("yt-remote-session-video-id"));
n7();a=k7();g.dc(a,m7());UXa(a)},$Xa=function(){if(!p7){var a=g.qs();
a&&(p7=new g.es(a))}},aYa=function(){$Xa();
return p7?!!p7.get("yt-remote-use-staging-server"):!1},q7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},bYa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},cYa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},r7=function(a){a.length?dYa(a.shift(),function(){r7(a)}):s7()},eYa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},dYa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.yk(d,g.Vr(a));(document.head||document.documentElement).appendChild(d)},fYa=function(){var a=q7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},s7=function(){var a=cYa();
a&&a(!1,"No cast extension found")},t7=function(){if(gYa){var a=2,b=cYa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;dYa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",s7,c)}},hYa=function(){t7();
var a=fYa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");r7(a)},jYa=function(){t7();
var a=fYa();a.push.apply(a,g.v(iYa.map(eYa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");r7(a)},u7=function(a,b,c){g.H.call(this);
this.J=null!=c?(0,g.Qa)(a,c):a;this.Yf=b;this.D=(0,g.Qa)(this.wR,this);this.i=!1;this.u=0;this.B=this.Pb=null;this.C=[]},v7=function(a,b,c){g.H.call(this);
this.C=null!=c?a.bind(c):a;this.Yf=b;this.B=null;this.i=!1;this.u=0;this.Pb=null},w7=function(a){a.Pb=g.mi(function(){a.Pb=null;
a.i&&!a.u&&(a.i=!1,w7(a))},a.Yf);
var b=a.B;a.B=null;a.C.apply(null,b)},x7=function(){},y7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},A7=function(a){z7.dispatchEvent(new kYa(z7,a))},kYa=function(a,b){g.Ee.call(this,"statevent",a);
this.stat=b},B7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.sl(this);this.J=new g.li;this.J.setInterval(250)},mYa=function(a,b,c){a.du=1;
a.un=Y6(b.clone());a.Hq=c;a.D=!0;lYa(a,null)},C7=function(a,b,c,d,e){a.du=1;
a.un=Y6(b.clone());a.Hq=null;a.D=c;e&&(a.AO=!1);lYa(a,d)},lYa=function(a,b){a.Mt=Date.now();
D7(a);a.Qo=a.un.clone();Z6(a.Qo,"t",a.K);a.SB=0;a.Of=a.i.WD(a.i.Ix()?b:null);0<a.IC&&(a.gB=new v7((0,g.Qa)(a.BP,a,a.Of),a.IC));a.C.Ra(a.Of,"readystatechange",a.xR);b=a.ip?g.gf(a.ip):{};a.Hq?(a.PB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Of.send(a.Qo,a.PB,a.Hq,b)):(a.PB="GET",a.AO&&!g.Ie&&(b.Connection="close"),a.Of.send(a.Qo,a.PB,null,b));a.i.Mj(1)},oYa=function(a,b){var c=a.SB,d=b.indexOf("\n",c);
if(-1==d)return E7;c=Number(b.substring(c,d));if(isNaN(c))return nYa;d+=1;if(d+c>b.length)return E7;b=b.substr(d,c);a.SB=d+c;return b},qYa=function(a,b){a.Mt=Date.now();
D7(a);var c=b?window.location.hostname:"";a.Qo=a.un.clone();g.ml(a.Qo,"DOMAIN",c);g.ml(a.Qo,"t",a.K);try{a.bk=new ActiveXObject("htmlfile")}catch(m){F7(a);a.dn=7;A7(22);G7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in H7)f=H7[f];else if(f in pYa)f=H7[f]=pYa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
H7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.wg(g.Qf("b/12014412"),d);a.bk.open();a.bk.write(g.sg(c));a.bk.close();a.bk.parentWindow.m=(0,g.Qa)(a.wX,a);a.bk.parentWindow.d=(0,g.Qa)(a.IN,a,!0);a.bk.parentWindow.rpcClose=(0,g.Qa)(a.IN,a,!1);c=a.bk.createElement("DIV");a.bk.parentWindow.document.body.appendChild(c);d=g.gg(a.Qo.toString());d=g.Sg(g.cg(d));d=g.wg(g.Qf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.yg(c,d);a.i.Mj(1)},D7=function(a){a.SH=Date.now()+
a.u;
rYa(a,a.u)},rYa=function(a,b){if(null!=a.Au)throw Error("WatchDog timer not null");
a.Au=y7((0,g.Qa)(a.DX,a),b)},I7=function(a){a.Au&&(g.C.clearTimeout(a.Au),a.Au=null)},G7=function(a){a.i.yf()||a.Dp||a.i.By(a)},F7=function(a){I7(a);
g.Be(a.gB);a.gB=null;a.J.stop();g.Ol(a.C);if(a.Of){var b=a.Of;a.Of=null;b.abort();b.dispose()}a.bk&&(a.bk=null)},J7=function(a,b){try{a.i.BN(a,b),a.i.Mj(4)}catch(c){}},tYa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;sYa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){tYa(a,b,c,d,f)},f)})}},sYa=function(a,b,c){var d=new Image;
d.onload=function(){try{K7(d),c(!0)}catch(e){}};
d.onerror=function(){try{K7(d),c(!1)}catch(e){}};
d.onabort=function(){try{K7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
BXa(d,a)},K7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},uYa=function(a){this.i=a;
this.u=new x7},vYa=function(a){var b=L7(a.i,a.ov,"/mail/images/cleardot.gif");
Y6(b);tYa(b.toString(),5E3,(0,g.Qa)(a.hS,a),3,2E3);a.Mj(1)},N7=function(a){var b=a.i.X;
if(null!=b)A7(5),b?(A7(11),M7(a.i,a,!1)):(A7(12),M7(a.i,a,!0));else if(a.uh=new B7(a,void 0,void 0,void 0),a.uh.ip=a.JC,b=a.i,b=L7(b,b.Ix()?a.Wu:null,a.KC),A7(5),!g.Ic||g.Bc(10))Z6(b,"TYPE","xmlhttp"),C7(a.uh,b,!1,a.Wu,!1);else{Z6(b,"TYPE","html");var c=a.uh;a=!!a.Wu;c.du=3;c.un=Y6(b.clone());qYa(c,a)}},O7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new x7;this.S=a||null;this.X=null!=b?b:null;this.J=c||!1},wYa=function(a,b){this.i=a;
this.map=b;this.context=null},xYa=function(a,b,c,d){g.Ee.call(this,"timingevent",a);
this.size=b;this.yx=d},yYa=function(a){g.Ee.call(this,"serverreachability",a)},BYa=function(a){zYa(a);
if(3==a.i){var b=a.Lw++,c=a.oz.clone();g.ml(c,"SID",a.B);g.ml(c,"RID",b);g.ml(c,"TYPE","terminate");P7(a,c);b=new B7(a,a.B,b,void 0);b.du=2;b.un=Y6(c.clone());BXa(new Image,b.un.toString());b.Mt=Date.now();D7(b)}AYa(a)},CYa=function(a){a.LS(1,0);
a.oz=L7(a,null,a.LC);Q7(a)},zYa=function(a){a.zn&&(a.zn.abort(),a.zn=null);
a.Qe&&(a.Qe.cancel(),a.Qe=null);a.Rl&&(g.C.clearTimeout(a.Rl),a.Rl=null);R7(a);a.Yg&&(a.Yg.cancel(),a.Yg=null);a.Jn&&(g.C.clearTimeout(a.Jn),a.Jn=null)},DYa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new wYa(a.xU++,b));2!=a.i&&3!=a.i||Q7(a)},EYa=function(a){var b=0;
a.Qe&&b++;a.Yg&&b++;return b},Q7=function(a){a.Yg||a.Jn||(a.Jn=y7((0,g.Qa)(a.GN,a),0),a.Hs=0)},GYa=function(a,b){if(1==a.i){if(!b){a.Lw=Math.floor(1E5*Math.random());
b=a.Lw++;var c=new B7(a,"",b,void 0);c.ip=a.vk;var d=S7(a),e=a.oz.clone();g.ml(e,"RID",b);g.ml(e,"CVER","1");P7(a,e);mYa(c,e,d);a.Yg=c;a.i=2}}else 3==a.i&&(b?FYa(a,b):0==a.u.length||a.Yg||FYa(a))},FYa=function(a,b){if(b)if(6<a.Ep){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Lw-1;b=S7(a)}else c=b.S,b=b.Hq;else c=a.Lw++,b=S7(a);var d=a.oz.clone();g.ml(d,"SID",a.B);g.ml(d,"RID",c);g.ml(d,"AID",a.kt);P7(a,d);c=new B7(a,a.B,c,a.Hs+1);c.ip=a.vk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Yg=c;mYa(c,d,b)},P7=function(a,b){a.Pf&&(a=a.Pf.aL())&&g.Oe(a,function(c,d){g.ml(b,d,c)})},S7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Ep&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={rr:e.rr},f++){e.rr=a.u[f].i;var h=a.u[f].map;e.rr=6>=a.Ep?f:e.rr-d;try{g.Oe(h,function(l){return function(m,n){c.push("req"+l.rr+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.rr+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},HYa=function(a){a.Qe||a.Rl||(a.K=1,a.Rl=y7((0,g.Qa)(a.FN,a),0),a.gs=0)},T7=function(a){if(a.Qe||a.Rl||3<=a.gs)return!1;
a.K++;a.Rl=y7((0,g.Qa)(a.FN,a),IYa(a,a.gs));a.gs++;return!0},M7=function(a,b,c){a.NB=c;
a.wk=b.Il;a.J||CYa(a)},R7=function(a){null!=a.Mp&&(g.C.clearTimeout(a.Mp),a.Mp=null)},IYa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U7=function(a,b){if(2==b||9==b){var c=null;
a.Pf&&(c=null);var d=(0,g.Qa)(a.JY,a);c||(c=new g.el("//www.google.com/images/cleardot.gif"),Y6(c));sYa(c.toString(),1E4,d)}else A7(2);JYa(a,b)},JYa=function(a,b){a.i=0;
a.Pf&&a.Pf.nK(b);AYa(a);zYa(a)},AYa=function(a){a.i=0;
a.wk=-1;if(a.Pf)if(0==a.C.length&&0==a.u.length)a.Pf.ID();else{g.gc(a.C);var b=g.gc(a.u);a.C.length=0;a.u.length=0;a.Pf.ID(b)}},L7=function(a,b,c){var d=g.nl(c);
if(""!=d.i)b&&g.gl(d,b+"."+d.i),g.hl(d,d.B);else{var e=window.location;d=KXa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Lv&&g.Oe(a.Lv,function(f,h){g.ml(d,h,f)});
g.ml(d,"VER",a.Ep);P7(a,d);return d},KYa=function(){},LYa=function(){this.i=[];
this.u=[]},MYa=function(a,b){this.action=a;
this.params=b||{}},V7=function(a,b){g.H.call(this);
this.i=new g.L(this.nX,0,this);g.I(this,this.i);this.Yf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.Qa)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.Qa)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},W7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ya=a;this.J=b;this.B=new g.ds;this.u=new V7(this.lY,this);this.i=null;this.Z=!1;this.D=null;this.X="";this.S=this.C=0;this.K=[];this.Aa=c;this.ma=d;this.Ba=e},NYa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.NB,sessionId:a.i.B,arrayId:a.i.kt}},OYa=function(a,b){a.S=b||0;
a.u.stop();X7(a);a.i&&(3==a.i.getState()&&GYa(a.i),BYa(a.i));a.S=0},Y7=function(a){return!!a.i&&3==a.i.getState()},X7=function(a){if(a.i){var b=a.ma(),c=a.i.vk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.vk=c}},Z7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.bj(4,a))||"";b&&(this.port=":"+b);this.domain=g.cj(a)||"";a=g.wb();0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.vb(a,"10.0")&&(this.u=!1))},$7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.nj(c+b,{})},a8=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.C,d,!0),onError:g.Sa(a.B,e),onTimeout:g.Sa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.bu(b,a)},SYa=function(){var a=PYa;
QYa();b8.push(a);RYa()},c8=function(a,b){QYa();
var c=TYa(a,String(b));g.ac(b8)?UYa(c):(RYa(),g.sc(b8,function(d){d(c)}))},QYa=function(){b8||(b8=g.Ia("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",b8,void 0))},UYa=function(a){var b=(d8+1)%50;
d8=b;e8[b]=a;f8||(f8=49==b)},RYa=function(){var a=b8;
if(e8[0]){var b=f8?d8:-1;do{b=(b+1)%50;var c=e8[b];g.sc(a,function(d){d(c)})}while(b!=d8);
e8=Array(50);d8=-1;f8=!1}},TYa=function(a,b){var c=(Date.now()-VYa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g8=function(a){g.Jx.call(this);
this.J=a;this.screens=[]},WYa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},XYa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.aq(a.screens,function(f){return!!i7(b,f)});
for(var d=0,e=b.length;d<e;d++)c=WYa(a,b[d])||c;return c},YYa=function(a,b){var c=a.screens.length;
a.screens=g.aq(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},h8=function(a,b,c,d,e){g.Jx.call(this);
this.B=a;this.K=b;this.C=c;this.J=d;this.D=e;this.u=0;this.i=null;this.Pb=NaN},j8=function(a){g8.call(this,"LocalScreenService");
this.u=a;this.i=NaN;i8(this);this.info("Initializing with "+g7(this.screens))},ZYa=function(a){if(a.screens.length){var b=g.co(a.screens,function(d){return d.id}),c=$7(a.u,"/pairing/get_lounge_token_batch");
a8(a.u,c,{screen_ids:b.join(",")},(0,g.Qa)(a.mT,a),(0,g.Qa)(a.lT,a))}},i8=function(a){if(g.P("deprecate_pair_servlet_enabled"))return XYa(a,[]);
var b=QXa(WXa());b=g.aq(b,function(c){return!c.uuid});
return XYa(a,b)},k8=function(a,b){YXa(g.co(a.screens,OXa));
b&&XXa()},m8=function(a,b){g.Jx.call(this);
this.J=b;b=(b=g.By("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.J(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.$b(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;l8("Initialized with "+g.Ti(this.i))},n8=function(a,b,c){var d=$7(a.D,"/pairing/get_screen_availability");
a8(a.D,d,{lounge_token:b.token},(0,g.Qa)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.Qa)(function(){c(!1)},a))},o8=function(a,b){a:if($6(b)!=$6(a.i))var c=!1;
else{c=g.We(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(l8("Updated online screens: "+g.Ti(a.i)),a.i=b,a.ea("screenChange"));$Ya(a)},p8=function(a){isNaN(a.B)||g.Yt(a.B);
a.B=g.Wt((0,g.Qa)(a.IG,a),0<a.C&&a.C<g.Ta()?2E4:1E4)},l8=function(a){c8("OnlineScreenService",a)},aZa=function(a){var b={};
g.sc(a.J(),function(c){c.token?b[c.token]=c.id:this.ye("Requesting availability of screen w/o lounge token.")});
return b},$Ya=function(a){a=g.We(g.Pe(a.i,function(b){return b}));
g.oc(a);a.length?g.Ay("yt-remote-online-screen-ids",a.join(","),60):g.Cy("yt-remote-online-screen-ids")},q8=function(a,b){b=void 0===b?!1:b;
g8.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};bZa(this)},dZa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Ih(),l=c?j7(h,c):null;c&&(a.K||l)||(l=j7(h,b));if(l){l.uuid=b;var m=r8(a,l);n8(a.i,m,function(n){e(n?m:null)})}else c?cZa(a,c,(0,g.Qa)(function(n){var p=r8(this,new d7({name:d,
screenId:c,loungeToken:n,dialId:b||""}));n8(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},eZa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},fZa=function(a,b,c){n8(a.i,b,c)},cZa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.bu($7(a.C,"/pairing/get_lounge_token_batch"),e)},gZa=function(a){a.screens=a.u.Ih();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+g7(a.screens))},bZa=function(a){s8(a);
a.u=new j8(a.C);a.u.subscribe("screenChange",(0,g.Qa)(a.vT,a));gZa(a);a.K||(a.B=QXa(g.By("yt-remote-automatic-screen-cache")||[]));s8(a);a.info("Initializing automatic screens: "+g7(a.B));a.i=new m8(a.C,(0,g.Qa)(a.Ih,a,!0));a.i.subscribe("screenChange",(0,g.Qa)(function(){this.ea("onlineScreenChange")},a))},r8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=j7(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||hZa(a));s8(a);a.D[b.uuid]=b.id;g.Ay("yt-remote-device-id-map",a.D,31536E3);return b},hZa=function(a){a=g.aq(a.B,function(b){return"shortLived"!=b.idType});
g.Ay("yt-remote-automatic-screen-cache",g.co(a,OXa))},s8=function(a){a.D=g.By("yt-remote-device-id-map")||{}},t8=function(a,b,c){g.Jx.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},u8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},iZa=function(a,b){a.C&&(a.C.token=b,r8(a.B,a.C));
a.ea("sessionScreen",a.C)},v8=function(a,b){c8(a.Ba,b)},w8=function(a,b,c){t8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.ma=(0,g.Qa)(this.CR,this);this.Aa=(0,g.Qa)(this.HX,this);this.Z=g.Wt(function(){jZa(d,null)},12E4);
this.K=this.D=this.J=this.S=0;this.ya=!1;this.X="unknown"},x8=function(a,b){g.Yt(a.K);
a.K=0;0==b?kZa(a):a.K=g.Wt(function(){kZa(a)},b)},kZa=function(a){lZa(a,"getLoungeToken");
g.Yt(a.D);a.D=g.Wt(function(){mZa(a,null)},3E4)},lZa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Ti(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ja,(0,g.Qa)(function(){v8(this,"Failed to send message: "+b+".")},a)):v8(a,"Sending yt message without session: "+g.Ti(c))},y8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.nL(b,function(c){u8(a,c)},function(){return a.Bg()},5)):a.Bg(Error("Waiting for session status timed out."))},oZa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new d7(b);nZa(a,d,function(e){e?(a.ya=!0,r8(a.B,d),u8(a,d),a.X="unknown",x8(a,c)):(g.Gt(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Bg())},5)},jZa=function(a,b){g.Yt(a.Z);
a.Z=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?oZa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Gt(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),y8(a,b.screenId))):(g.Gt(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),y8(a,b.screenId)):y8(a,b.screenId):a.Bg(Error("Waiting for session status timed out."))},mZa=function(a,b){g.Yt(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.X=c,x8(a,3E4)):(iZa(a,b.loungeToken),a.ya=!1,a.X="unknown",x8(a,b.loungeTokenRefreshIntervalMs))},nZa=function(a,b,c,d){g.Yt(a.J);
a.J=0;fZa(a.B,b,function(e){e||0>d?c(e):a.J=g.Wt(function(){nZa(a,b,c,d-1)},300)})},pZa=function(a){g.Yt(a.S);
a.S=0;g.Yt(a.J);a.J=0;g.Yt(a.Z);a.Z=0;g.Yt(a.D);a.D=0;g.Yt(a.K);a.K=0},z8=function(a,b,c,d){t8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.Ma=c;this.Ka=null;this.Z=g.Ja;this.X=NaN;this.Ja=(0,g.Qa)(this.DR,this);this.D=g.Ja;this.K=this.J=0;this.ma=!1;this.ya="unknown"},A8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},qZa=function(a){a.D=a.B.eJ(a.Aa,a.i.label,a.i.friendlyName,A8(a),function(b,c){a.D=g.Ja;
a.ma=!0;u8(a,b);"shortLived"==b.idType&&0<c&&B8(a,c)},function(b){a.D=g.Ja;
a.Bg(b)})},rZa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.Ma;aYa()&&(b.env_useStageMdx=1);return g.lj(b)},C8=function(a){return new Promise(function(b){a.Aa=h7();
if(a.Ka){var c=new chrome.cast.DialLaunchResponse(!0,rZa(a));b(c);qZa(a)}else a.Z=function(){g.Yt(a.X);a.Z=function(){};
a.X=NaN;var d=new chrome.cast.DialLaunchResponse(!0,rZa(a));b(d);qZa(a)},a.X=g.Wt(function(){a.Z()},100)})},tZa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new d7(b);return(new Promise(function(e){sZa(a,d,function(f){f?(a.ma=!0,r8(a.B,d),u8(a,d),B8(a,c)):g.Gt(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):C8(a)})},uZa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){dZa(a.B,c,b,d,function(f){f&&f.token&&u8(a,f);e(f)},function(f){v8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):C8(a)})},sZa=function(a,b,c,d){g.Yt(a.J);
a.J=0;fZa(a.B,b,function(e){e||0>d?c(e):a.J=g.Wt(function(){sZa(a,b,c,d-1)},300)})},B8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
A8(a)&&(g.Yt(a.K),a.K=0,0==b?vZa(a):a.K=g.Wt(function(){vZa(a)},b))},vZa=function(a){A8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ya=c,B8(a,3E4)):(a.ma=!1,a.ya="unknown",iZa(a,b.loungeToken),B8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ya="noLoungeTokenResponse";B8(a,3E4)})},wZa=function(a){g.Yt(a.J);
a.J=0;g.Yt(a.K);a.K=0;a.D();a.D=function(){};
g.Yt(a.X)},D8=function(a,b){t8.call(this,a,b,"ManualSession");
this.u=g.Wt((0,g.Qa)(this.nt,this,null),150)},E8=function(a,b){g.Jx.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.X=b.disableCastApi||!1;this.J=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.Qa)(this.zW,this)},xZa=function(a,b){return b?g.Wb(a.B,function(c){return e7(b,c.label)},a):null},F8=function(a){c8("Controller",a)},PYa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G8=function(a){return a.K||!!a.B.length||!!a.i},H8=function(a,b,c){b!=a.i&&(g.Be(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.Qa)(a.EN,a,b)),b.subscribe("sessionFailed",function(){return yZa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.nt(null)):a.ea("yt-remote-cast2-session-change",null))},yZa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},zZa=function(a){var b=a.u.dJ(),c=a.i&&a.i.i;
a=g.co(b,function(d){c&&e7(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=xZa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},EZa=function(a,b,c,d){d.disableCastApi?I8("Cannot initialize because disabled by Mdx config."):AZa()?BZa(b,d)&&(J8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?CZa(a,c):(window.__onGCastApiAvailable=function(e,f){e?CZa(a,c):(K8("Failed to load cast API: "+f),L8(!1),J8(!1),g.Cy("yt-remote-cast-available"),g.Cy("yt-remote-cast-receiver"),
DZa(),c(!1))},d.loadCastApiSetupScript?g.Ey("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=q7()&&hYa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?s7():89<=q7()?jYa():(t7(),r7(iYa.map(eYa))))):I8("Cannot initialize because not running Chrome")},DZa=function(){I8("dispose");
var a=M8();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);FZa(!1);g.qv(N8);N8.length=0},O8=function(){return!!g.By("yt-remote-cast-installed")},GZa=function(){var a=g.By("yt-remote-cast-receiver");
return a?a.friendlyName:null},HZa=function(){I8("clearCurrentReceiver");
g.Cy("yt-remote-cast-receiver")},IZa=function(){return O8()?M8()?M8().getCastSession():(K8("getCastSelector: Cast is not initialized."),null):(K8("getCastSelector: Cast API is not installed!"),null)},Q8=function(){O8()?M8()?P8()?(I8("Requesting cast selector."),M8().requestSession()):(I8("Wait for cast API to be ready to request the session."),N8.push(g.pv("yt-remote-cast2-api-ready",Q8))):K8("requestCastSelector: Cast is not initialized."):K8("requestCastSelector: Cast API is not installed!")},R8=
function(a,b){P8()?M8().setConnectedScreenStatus(a,b):K8("setConnectedScreenStatus called before ready.")},AZa=function(){var a=0<=g.wb().search(/ (CrMo|Chrome|CriOS)\//);
return g.aA||a},JZa=function(a,b){M8().init(a,b)},BZa=function(a,b){var c=!1;
M8()||(a=new E8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Ay("yt-remote-cast-available",d);b7("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){I8("onReceiverSelected: "+d.friendlyName);
g.Ay("yt-remote-cast-receiver",d);b7("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){I8("onReceiverResumed: "+d.friendlyName);
g.Ay("yt-remote-cast-receiver",d);b7("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){I8("onSessionChange: "+f7(d));
d||g.Cy("yt-remote-cast-receiver");b7("yt-remote-cast2-session-change",d)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
I8("cloudview.createSingleton_: "+c);return c},M8=function(){return g.Ia("yt.mdx.remote.cloudview.instance_")},CZa=function(a,b){L8(!0);
J8(!1);JZa(a,function(c){c?(FZa(!0),g.rv("yt-remote-cast2-api-ready")):(K8("Failed to initialize cast API."),L8(!1),g.Cy("yt-remote-cast-available"),g.Cy("yt-remote-cast-receiver"),DZa());b(c)})},I8=function(a){c8("cloudview",a)},K8=function(a){c8("cloudview",a)},L8=function(a){I8("setCastInstalled_ "+a);
g.Ay("yt-remote-cast-installed",a)},P8=function(){return!!g.Ia("yt.mdx.remote.cloudview.apiReady_")},FZa=function(a){I8("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J8=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},S8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.K=0;this.trackData=null;this.hasNext=this.Wk=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},T8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Wk=!1;a.hasNext=!1;a.K=0;a.J=g.Ta();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},U8=function(a){return a.Jc()?(g.Ta()-a.J)/1E3:0},V8=function(a,b){a.K=b;
a.J=g.Ta()},W8=function(a){switch(a.playerState){case 1:case 1081:return(g.Ta()-a.J)/1E3+a.K;
case -1E3:return 0}return a.K},X8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T8(a)},Y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.hf(a.trackData);b.hasPrevious=a.Wk;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},$8=function(a,b){g.Jx.call(this);
this.B=0;this.C=a;this.J=[];this.D=new LYa;this.u=this.i=null;this.X=(0,g.Qa)(this.hV,this);this.K=(0,g.Qa)(this.Uw,this);this.S=(0,g.Qa)(this.gV,this);this.Z=(0,g.Qa)(this.oV,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ZG,this),KZa(this))):c=3;0!=c&&(b?this.ZG(c):g.Wt((0,g.Qa)(function(){this.ZG(c)},this),0));
(a=IZa())&&Z8(this,a);this.subscribe("yt-remote-cast2-session-change",this.Z)},a9=function(a){return new S8(a.C.getPlayerContextData())},KZa=function(a){g.sc("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.J.push(this.C.subscribe(b,g.Sa(this.xW,b),this))},a)},LZa=function(a){g.sc(a.J,function(b){this.C.unsubscribeByKey(b)},a);
a.J.length=0},b9=function(a){return 1==a.getState()},c9=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},e9=function(a,b,c){var d=a9(a);
V8(d,c);-1E3!=d.playerState&&(d.playerState=b);d9(a,d)},f9=function(a,b,c){a.C.sendMessage(b,c)},d9=function(a,b){LZa(a);
a.C.setPlayerContextData(Y8(b));KZa(a)},Z8=function(a,b){a.u&&(a.u.removeUpdateListener(a.X),a.u.removeMediaListener(a.K),a.Uw(null));
a.u=b;a.u&&(c8("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.X),a.u.addMediaListener(a.K),a.u.media.length&&a.Uw(a.u.media[0]))},MZa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=a9(a);b.contentId!=d.videoId&&c8("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V8(d,a.i.getEstimatedTime());d9(a,d)}else c8("CP","No cast media video. Ignoring state update.")},g9=function(a,b,c){return(0,g.Qa)(function(d){this.ye("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.ye("Retrying "+b+" using MDx browser channel."),f9(this,b,c))},a)},h9=function(a,b,c,d){d=void 0===d?!1:d;
g.Jx.call(this);var e=this;this.D=NaN;this.ya=!1;this.S=this.K=this.Z=this.ma=NaN;this.X=[];this.C=this.J=this.B=this.zc=this.i=null;this.Ja=a;this.Ba=d;this.X.push(g.Uu(window,"beforeunload",function(){e.Ds(2)}));
this.u=[];this.zc=new S8;this.Ka=b.id;this.Aa=b.idType;this.i=NZa(this,c);this.i.subscribe("handlerOpened",this.lV,this);this.i.subscribe("handlerClosed",this.iV,this);this.i.subscribe("handlerError",this.jV,this);this.i.subscribe("handlerMessage",this.kV,this);this.i.sB(b.token);this.subscribe("remoteQueueChange",function(){var f=this.zc.videoId;g.Dy()&&g.Ay("yt-remote-session-video-id",f)},this)},OZa=function(a){return g.Wb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},i9=function(a){c8("conn",
a)},NZa=function(a,b){return new W7($7(a.Ja,"/bc"),b,!1,function(){return a.oI()},"shortLived"==a.Aa)},j9=function(a,b){a.ea("proxyStateChange",b)},PZa=function(a){a.D=g.Wt(function(){i9("Connecting timeout");
a.Ds(1)},2E4)},k9=function(a){g.Yt(a.D);
a.D=NaN},l9=function(a){g.Yt(a.ma);
a.ma=NaN},QZa=function(a){m9(a);
a.Z=g.Wt(function(){n9(a,"getNowPlaying")},2E4)},m9=function(a){g.Yt(a.Z);
a.Z=NaN},SZa=function(a,b){var c=null;
if(b){var d=OZa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Ha("yt.mdx.remote.remoteClient_",c,void 0);b&&(k9(a),l9(a));c=Y7(a.i)&&isNaN(a.D);b==c?b&&(j9(a,1),n9(a,"getSubtitlesTrack")):b?(a.mL()&&a.zc.reset(),j9(a,1),n9(a,"getNowPlaying"),RZa(a)):a.Ds(1)},TZa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.zc.videoId&&(g.af(b.params)?a.zc.trackData=null:a.zc.trackData=b.params,a.ea("remotePlayerChange"))},UZa=function(a,b,c){var d=b.params.videoId||b.params.video_id,e=parseInt(b.params.currentIndex,10);
a.zc.listId=b.params.listId||a.zc.listId;X8(a.zc,d,e);a.ea("remoteQueueChange",c)},WZa=function(a,b){b.params=b.params||{};
UZa(a,b,"NOW_PLAYING_MAY_CHANGE");VZa(a,b);a.ea("autoplayDismissed")},VZa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V8(a.zc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.zc.playerState&&(c=-1E3);a.zc.playerState=c;c=Number(b.params.loadedTime);a.zc.S=isNaN(c)?0:c;a.zc.Vj(Number(b.params.duration));c=a.zc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.zc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.zc.playerState?QZa(a):m9(a);a.ea("remotePlayerChange")},XZa=function(a,b){if(-1E3!=a.zc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.zc.playerState=c;b=parseInt(b.params.currentTime,10);V8(a.zc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},YZa=function(a,b){var c="true"==b.params.muted;
a.zc.volume=parseInt(b.params.volume,10);a.zc.muted=c;a.ea("remotePlayerChange")},ZZa=function(a,b){a.J=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},$Za=function(a,b){var c="true"==b.params.hasNext;
a.zc.Wk="true"==b.params.hasPrevious;a.zc.hasNext=c;a.ea("previousNextChange")},RZa=function(a){g.Yt(a.S);
a.S=g.Wt(function(){a.Ds(1)},864E5)},n9=function(a,b,c){c?i9("Sending: action="+b+", params="+g.Ti(c)):i9("Sending: action="+b);
a.i.sendMessage(b,c)},o9=function(a){g8.call(this,"ScreenServiceProxy");
this.Xe=a;this.i=[];this.i.push(this.Xe.$_s("screenChange",(0,g.Qa)(this.ZP,this)));this.i.push(this.Xe.$_s("onlineScreenChange",(0,g.Qa)(this.eW,this)))},d_a=function(a,b){$Xa();
if(!p7||!p7.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;SXa();n7();p9||(p9=new Z7(b?b.loungeApiHost:void 0),aYa()&&(p9.i="/api/loungedev"));q9||(q9=g.Ia("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",q9,void 0));a_a();var c=r9();if(!c){var d=new q8(p9,b?b.disableAutomaticScreenCache||!1:!1);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=r9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Ha("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);EZa(a,d,function(f){f?s9()&&R8(s9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){b7("yt-remote-receiver-availability-change")})},e)}b&&!g.Ia("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),t9("Initializing: "+
g.Ti(b)),u9.push(g.pv("yt-remote-cast2-api-ready",function(){b7("yt-remote-api-ready")})),u9.push(g.pv("yt-remote-cast2-availability-change",function(){b7("yt-remote-receiver-availability-change")})),u9.push(g.pv("yt-remote-cast2-receiver-selected",function(){v9(null);
b7("yt-remote-auto-connect","cast-selector-receiver")})),u9.push(g.pv("yt-remote-cast2-receiver-resumed",function(){b7("yt-remote-receiver-resumed","cast-selector-receiver")})),u9.push(g.pv("yt-remote-cast2-session-change",b_a)),u9.push(g.pv("yt-remote-connection-change",function(f){f?R8(s9(),"YouTube TV"):w9()||(R8(null,null),HZa())})),u9.push(g.pv("yt-remote-cast2-session-failed",function(){b7("yt-remote-connection-failed")})),a=x9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.P("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),t9(" -- with channel params: "+g.Ti(a)),a?(g.Ay("yt-remote-session-app",a.app),g.Ay("yt-remote-session-name",a.name)):(g.Cy("yt-remote-session-app"),g.Cy("yt-remote-session-name")),g.Ha("yt.mdx.remote.channelParams_",a,void 0),c.start(),s9()||c_a())}},e_a=function(){var a=r9().Xe.$_gos();
var b=y9();b&&z9()&&(i7(a,b)||a.push(b));return RXa(a)},A9=function(){var a=f_a();
!a&&O8()&&GZa()&&(a={key:"cast-selector-receiver",name:GZa()});return a},f_a=function(){var a=e_a(),b=y9();
b||(b=w9());return g.Wb(a,function(c){return b&&e7(b,c.key)?!0:!1})},y9=function(){var a=s9();
if(!a)return null;var b=r9().Ih();return j7(b,a)},b_a=function(a){t9("remote.onCastSessionChange_: "+f7(a));
if(a){var b=y9();if(b&&b.id==a.id){if(R8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))B9&&(B9.token=a),(b=z9())&&b.sB(a)}else b&&C9(),D9(a,1)}else z9()&&C9()},C9=function(){P8()?M8().stopSession():K8("stopSession called before API ready.");
var a=z9();a&&(a.disconnect(1),E9(null))},F9=function(){var a=z9();
return!!a&&3!=a.getProxyState()},t9=function(a){c8("remote",a)},r9=function(){if(!G9){var a=g.Ia("yt.mdx.remote.screenService_");
G9=a?new o9(a):null}return G9},s9=function(){return g.Ia("yt.mdx.remote.currentScreenId_")},g_a=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},h_a=function(){return g.Ia("yt.mdx.remote.connectData_")},v9=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},z9=function(){return g.Ia("yt.mdx.remote.connection_")},E9=function(a){var b=z9();
v9(null);a||g_a("");g.Ha("yt.mdx.remote.connection_",a,void 0);q9&&(g.sc(q9,function(c){c(a)}),q9.length=0);
b&&!a?b7("yt-remote-connection-change",!1):!b&&a&&b7("yt-remote-connection-change",!0)},w9=function(){var a=g.Dy();
if(!a)return null;var b=r9();if(!b)return null;b=b.Ih();return j7(b,a)},D9=function(a,b){s9();
y9()&&y9();if(H9)B9=a;else{g_a(a.id);var c=g.Ia("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new h9(p9,a,x9(),c);a.connect(b,h_a());a.subscribe("beforeDisconnect",function(d){b7("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){z9()&&(z9(),E9(null))});
a.subscribe("browserChannelAuthError",function(){var d=y9();d&&"shortLived"==d.idType&&(P8()?M8().handleBrowserChannelAuthError():K8("refreshLoungeToken called before API ready."))});
E9(a)}},c_a=function(){var a=w9();
a?(t9("Resume connection to: "+f7(a)),D9(a,0)):(o7(),HZa(),t9("Skipping connecting because no session screen found."))},a_a=function(){var a=x9();
if(g.af(a)){a=m7();var b=g.By("yt-remote-session-name")||"",c=g.By("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},x9=function(){return g.Ia("yt.mdx.remote.channelParams_")||{}},I9=function(a,b,c){g.H.call(this);
var d=this;this.u=a;this.I=b;this.Xb=c;this.events=new g.yC(this);this.Z=this.events.T(this.I,"onVolumeChange",function(e){i_a(d,e)});
this.D=!1;this.J=new g.fJ(64);this.i=new g.L(this.NO,500,this);this.B=new g.L(this.OO,1E3,this);this.S=new u7(this.dZ,0,this);this.C={};this.X=new g.L(this.tP,1E3,this);this.K=new v7(this.seekTo,1E3,this);this.ma=g.Ja;g.I(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.PV);this.events.T(b,"captionschanged",this.eV);this.events.T(b,"captionssettingschanged",this.TO);this.events.T(b,"videoplayerreset",this.LA);this.events.T(b,"mdxautoplaycancel",function(){d.Xb.JK()});
a=this.Xb;a.isDisposed();a.subscribe("proxyStateChange",this.AN,this);a.subscribe("remotePlayerChange",this.Yw,this);a.subscribe("remoteQueueChange",this.LA,this);a.subscribe("previousNextChange",this.xN,this);a.subscribe("nowAutoplaying",this.rN,this);a.subscribe("autoplayDismissed",this.UM,this);g.I(this,this.i);g.I(this,this.B);g.I(this,this.S);g.I(this,this.X);g.I(this,this.K);this.TO();this.LA();this.Yw()},i_a=function(a,b){if(J9(a)){a.Xb.unsubscribe("remotePlayerChange",a.Yw,a);
var c=Math.round(b.volume);b=!!b.muted;var d=a9(a.Xb);if(c!==d.volume||b!==d.muted)a.Xb.setVolume(c,b),a.X.start();a.Xb.subscribe("remotePlayerChange",a.Yw,a)}},j_a=function(a){a.Sb(0);
a.i.stop();a.Yb(new g.fJ(64))},K9=function(a,b){if(J9(a)&&!a.D){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.kf(c,b));a.Xb.nI(a.I.getVideoData(1).videoId,c);a.C=a9(a.Xb).trackData}},L9=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Xb.playVideo(c.videoId,b,d,e,c.playerParams,c.Xa,HXa(c));a.Yb(new g.fJ(1))},k_a=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{KL:1});
c&&c.length?(a.I.setOption("captions","track",b),a.D=!1):(a.I.loadModule("captions"),a.D=!0)}else a.I.setOption("captions","track",{})},J9=function(a){return a9(a.Xb).videoId===a.I.getVideoData(1).videoId},M9=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},V:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",V:[{G:"div",L:"ytp-mdx-popup-title",va:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",va:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",V:[{G:"button",Ia:["ytp-button","ytp-mdx-privacy-popup-cancel"],va:"Cancel"},{G:"button",Ia:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],va:"Confirm"}]}]}]});this.i=new g.NK(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},N9=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",V:[{G:"div",L:"ytp-remote-display-status",V:[{G:"div",L:"ytp-remote-display-status-icon",V:[g.uxa()]},{G:"div",L:"ytp-remote-display-status-text",va:"{{statustext}}"}]}]});this.api=a;this.i=new g.NK(this,250);g.I(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);l_a(this,a.Ab())},l_a=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.T(b,128)?g.nH("Error on $RECEIVER_NAME",c):b.Jc()||g.T(b,4)?g.nH("Playing on $RECEIVER_NAME",c):g.nH("Connected to $RECEIVER_NAME",c);a.Qa("statustext",b);a.i.show()}else a.i.hide()},O9=function(a,b){g.wP.call(this,"Play on",0,a,b);
this.I=a;this.No={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},P9=function(a){g.vM.call(this,a);
this.fl={key:h7(),name:"This computer"};this.gi=null;this.subscriptions=[];this.vG=this.Xb=null;this.No=[this.fl];this.Bn=this.fl;this.Gd=new g.fJ(64);this.jM=0;this.Bf=-1;this.jx=!1;this.hx=this.Ht=null;if(!g.iE(this.player.U())&&!g.jE(this.player.U())){a=this.player;var b=g.YL(a);b&&(b=b.Rn())&&(b=new O9(a,b),g.I(this,b));b=new N9(a);g.I(this,b);g.hM(a,b.element,4);this.Ht=new M9;g.I(this,this.Ht);g.hM(a,this.Ht.element,4);this.jx=!!w9()}},Q9=function(a){a.hx&&(a.player.removeEventListener("presentingplayerstatechange",
a.hx),a.hx=null)},m_a=function(a,b,c){a.Gd=c;
a.player.ea("presentingplayerstatechange",new g.YG(c,b))},R9=function(a,b){if(b.key!==a.Bn.key)if(b.key===a.fl.key)C9();
else{var c;(c=!a.player.U().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.jx||!a.Ht);(c?0:g.yE(a.player.U())||g.BE(a.player.U()))&&n_a(a);a.Bn=b;if(!a.player.U().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.jE(a.player.U())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.U().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.pM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Xa,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=HXa(c))&&(a.locationInfo=c)}t9("Connecting to: "+g.Ti(b));"cast-selector-receiver"==b.key?(v9(a||null),b=a||null,P8()?M8().setLaunchParams(b):K8("setLaunchParams called before ready.")):!a&&F9()&&
s9()==b.key?b7("yt-remote-connection-change",!0):(C9(),v9(a||null),a=r9().Ih(),(b=j7(a,b.key))&&D9(b,1))}}},n_a=function(a){a.player.Ab().Jc()?a.player.pauseVideo():(a.hx=function(b){!a.jx&&g.$G(b,8)&&(a.player.pauseVideo(),Q9(a))},a.player.addEventListener("presentingplayerstatechange",a.hx));
a.Ht&&a.Ht.kd();z9()||(H9=!0)},pYa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},H7={"'":"\\'"},NXa={z_:"atp",Mba:"ska",raa:"que",f9:"mus",Lba:"sus",S4:"dsp",Paa:"seq",H8:"mic",O3:"dpa",O_:"cds",d9:"mlm",L3:"dsdtr",L9:"ntb"};c7.prototype.equals=function(a){return a?this.id==a.id:!1};
var p7,l7="",gYa=bYa("loadCastFramework")||bYa("loadCastApplicationFramework"),iYa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(u7,g.H);g.k=u7.prototype;g.k.vR=function(a){this.C=arguments;this.i=!1;this.Pb?this.B=g.Ta()+this.Yf:this.Pb=g.mi(this.D,this.Yf)};
g.k.stop=function(){this.Pb&&(g.C.clearTimeout(this.Pb),this.Pb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.J.apply(null,this.C)))};
g.k.xa=function(){this.stop();u7.xe.xa.call(this)};
g.k.wR=function(){this.Pb&&(g.C.clearTimeout(this.Pb),this.Pb=null);this.B?(this.Pb=g.mi(this.D,this.B-g.Ta()),this.B=null):this.u?this.i=!0:(this.i=!1,this.J.apply(null,this.C))};g.w(v7,g.H);g.k=v7.prototype;g.k.cJ=function(a){this.B=arguments;this.Pb||this.u?this.i=!0:w7(this)};
g.k.stop=function(){this.Pb&&(g.C.clearTimeout(this.Pb),this.Pb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Pb||(this.i=!1,w7(this))};
g.k.xa=function(){g.H.prototype.xa.call(this);this.stop()};x7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
x7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var z7=new g.Bf;g.w(kYa,g.Ee);g.k=B7.prototype;g.k.ip=null;g.k.Tm=!1;g.k.Au=null;g.k.SH=null;g.k.Mt=null;g.k.du=null;g.k.un=null;g.k.Qo=null;g.k.Hq=null;g.k.Of=null;g.k.SB=0;g.k.bk=null;g.k.PB=null;g.k.dn=null;g.k.Vu=-1;g.k.AO=!0;g.k.Dp=!1;g.k.IC=0;g.k.gB=null;var nYa={},E7={};g.k=B7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.xR=function(a){a=a.target;var b=this.gB;b&&3==g.Aj(a)?b.cJ():this.BP(a)};
g.k.BP=function(a){try{if(a==this.Of)a:{var b=g.Aj(this.Of),c=this.Of.u,d=this.Of.getStatus();if(g.Ic&&!g.Bc(10)||g.Ie&&!g.Ac("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Fj(this.Of))break a;this.Dp||4!=b||7==c||(8==c||0>=d?this.i.Mj(3):this.i.Mj(2));I7(this);var e=this.Of.getStatus();this.Vu=e;var f=g.Fj(this.Of);if(this.Tm=200==e){4==b&&F7(this);if(this.D){for(a=!0;!this.Dp&&this.SB<f.length;){var h=oYa(this,f);if(h==E7){4==b&&(this.dn=4,A7(15),a=!1);break}else if(h==nYa){this.dn=4;A7(16);a=!1;
break}else J7(this,h)}4==b&&0==f.length&&(this.dn=1,A7(17),a=!1);this.Tm=this.Tm&&a;a||(F7(this),G7(this))}else J7(this,f);this.Tm&&!this.Dp&&(4==b?this.i.By(this):(this.Tm=!1,D7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.dn=3,A7(13)):(this.dn=0,A7(14)),F7(this),G7(this)}}catch(l){this.Of&&g.Fj(this.Of)}finally{}};
g.k.wX=function(a){y7((0,g.Qa)(this.vX,this,a),0)};
g.k.vX=function(a){this.Dp||(I7(this),J7(this,a),D7(this))};
g.k.IN=function(a){y7((0,g.Qa)(this.uX,this,a),0)};
g.k.uX=function(a){this.Dp||(F7(this),this.Tm=a,this.i.By(this),this.i.Mj(4))};
g.k.cancel=function(){this.Dp=!0;F7(this)};
g.k.DX=function(){this.Au=null;var a=Date.now();0<=a-this.SH?(2!=this.du&&this.i.Mj(3),F7(this),this.dn=2,A7(18),G7(this)):rYa(this,this.SH-a)};
g.k.getLastError=function(){return this.dn};g.k=uYa.prototype;g.k.JC=null;g.k.uh=null;g.k.hB=!1;g.k.PO=null;g.k.nz=null;g.k.qF=null;g.k.KC=null;g.k.ai=null;g.k.Il=-1;g.k.Wu=null;g.k.ov=null;g.k.connect=function(a){this.KC=a;a=L7(this.i,null,this.KC);A7(3);this.PO=Date.now();var b=this.i.S;null!=b?(this.Wu=b[0],(this.ov=b[1])?(this.ai=1,vYa(this)):(this.ai=2,N7(this))):(Z6(a,"MODE","init"),this.uh=new B7(this,void 0,void 0,void 0),this.uh.ip=this.JC,C7(this.uh,a,!1,null,!0),this.ai=0)};
g.k.hS=function(a){if(a)this.ai=2,N7(this);else{A7(4);var b=this.i;b.wk=b.zn.Il;U7(b,9)}a&&this.Mj(2)};
g.k.WD=function(a){return this.i.WD(a)};
g.k.abort=function(){this.uh&&(this.uh.cancel(),this.uh=null);this.Il=-1};
g.k.yf=function(){return!1};
g.k.BN=function(a,b){this.Il=a.Vu;if(0==this.ai)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.wk=this.Il;U7(a,2);return}this.Wu=c[0];this.ov=c[1]}else a=this.i,a.wk=this.Il,U7(a,2);else if(2==this.ai)if(this.hB)A7(7),this.qF=Date.now();else if("11111"==b){if(A7(6),this.hB=!0,this.nz=Date.now(),a=this.nz-this.PO,!g.Ic||g.Bc(10)||500>a)this.Il=200,this.uh.cancel(),A7(12),M7(this.i,this,!0)}else A7(8),this.nz=this.qF=Date.now(),this.hB=!1};
g.k.By=function(){this.Il=this.uh.Vu;if(this.uh.Tm)0==this.ai?this.ov?(this.ai=1,vYa(this)):(this.ai=2,N7(this)):2==this.ai&&((!g.Ic||g.Bc(10)?!this.hB:200>this.qF-this.nz)?(A7(11),M7(this.i,this,!1)):(A7(12),M7(this.i,this,!0)));else{0==this.ai?A7(9):2==this.ai&&A7(10);var a=this.i;this.uh.getLastError();a.wk=this.Il;U7(a,2)}};
g.k.Ix=function(){return this.i.Ix()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Mj=function(a){this.i.Mj(a)};g.k=O7.prototype;g.k.vk=null;g.k.Lv=null;g.k.Yg=null;g.k.Qe=null;g.k.LC=null;g.k.oz=null;g.k.XJ=null;g.k.Cy=null;g.k.Lw=0;g.k.xU=0;g.k.Pf=null;g.k.Jn=null;g.k.Rl=null;g.k.Mp=null;g.k.zn=null;g.k.NB=null;g.k.kt=-1;g.k.iM=-1;g.k.wk=-1;g.k.Hs=0;g.k.gs=0;g.k.Ep=8;g.Ua(xYa,g.Ee);g.Ua(yYa,g.Ee);g.k=O7.prototype;g.k.connect=function(a,b,c,d,e){A7(0);this.LC=b;this.Lv=c||{};d&&void 0!==e&&(this.Lv.OSID=d,this.Lv.OAID=e);this.J?(y7((0,g.Qa)(this.tK,this,a),100),CYa(this)):this.tK(a)};
g.k.tK=function(a){this.zn=new uYa(this);this.zn.JC=this.vk;this.zn.u=this.D;this.zn.connect(a)};
g.k.yf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.GN=function(a){this.Jn=null;GYa(this,a)};
g.k.FN=function(){this.Rl=null;this.Qe=new B7(this,this.B,"rpc",this.K);this.Qe.ip=this.vk;this.Qe.IC=0;var a=this.XJ.clone();g.ml(a,"RID","rpc");g.ml(a,"SID",this.B);g.ml(a,"CI",this.NB?"0":"1");g.ml(a,"AID",this.kt);P7(this,a);if(!g.Ic||g.Bc(10))g.ml(a,"TYPE","xmlhttp"),C7(this.Qe,a,!0,this.Cy,!1);else{g.ml(a,"TYPE","html");var b=this.Qe,c=!!this.Cy;b.du=3;b.un=Y6(a.clone());qYa(b,c)}};
g.k.BN=function(a,b){if(0!=this.i&&(this.Qe==a||this.Yg==a))if(this.wk=a.Vu,this.Yg==a&&3==this.i)if(7<this.Ep){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Rl){if(this.Qe)if(this.Qe.Mt+3E3<this.Yg.Mt)R7(this),this.Qe.cancel(),this.Qe=null;else break a;T7(this);A7(19)}}else this.iM=a[1],0<this.iM-this.kt&&37500>a[2]&&this.NB&&0==this.gs&&!this.Mp&&(this.Mp=y7((0,g.Qa)(this.bV,this),6E3));else U7(this,11)}else null!=b&&U7(this,11);else if(this.Qe==
a&&R7(this),!g.jb(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.kt=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.Cy=c[2],c=c[3],null!=c?this.Ep=c:this.Ep=6,this.i=3,this.Pf&&this.Pf.pK(),this.XJ=L7(this,this.Ix()?this.Cy:null,this.LC),HYa(this)):"stop"==c[0]&&U7(this,7):3==this.i&&("stop"==c[0]?U7(this,7):"noop"!=c[0]&&this.Pf&&this.Pf.oK(c),this.gs=0)};
g.k.bV=function(){null!=this.Mp&&(this.Mp=null,this.Qe.cancel(),this.Qe=null,T7(this),A7(20))};
g.k.By=function(a){if(this.Qe==a){R7(this);this.Qe=null;var b=2}else if(this.Yg==a)this.Yg=null,b=1;else return;this.wk=a.Vu;if(0!=this.i)if(a.Tm)if(1==b){b=Date.now()-a.Mt;var c=z7;c.dispatchEvent(new xYa(c,a.Hq?a.Hq.length:0,b,this.Hs));Q7(this);this.C.length=0}else HYa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.wk)){if(d=1==b)this.Yg||this.Jn||1==this.i||2<=this.Hs?d=!1:(this.Jn=y7((0,g.Qa)(this.GN,this,a),IYa(this,this.Hs)),this.Hs++,d=!0);d=!(d||2==b&&T7(this))}if(d)switch(c){case 1:U7(this,
5);break;case 4:U7(this,10);break;case 3:U7(this,6);break;case 7:U7(this,12);break;default:U7(this,2)}}};
g.k.LS=function(a){if(!g.$b(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.JY=function(a){a?A7(2):(A7(1),JYa(this,8))};
g.k.WD=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.uj;a.S=!1;return a};
g.k.isActive=function(){return!!this.Pf&&this.Pf.isActive(this)};
g.k.Mj=function(a){var b=z7;b.dispatchEvent(new yYa(b,a))};
g.k.Ix=function(){return!(!g.Ic||g.Bc(10))};
g.k=KYa.prototype;g.k.pK=function(){};
g.k.oK=function(){};
g.k.nK=function(){};
g.k.ID=function(){};
g.k.aL=function(){return{}};
g.k.isActive=function(){return!0};g.k=LYa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.$b(this.i,a)||g.$b(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.zRa)(b,a);0<=c?(g.cc(b,c),b=!0):b=!1;return b||g.dc(this.u,a)};
g.k.Ai=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(V7,g.H);g.k=V7.prototype;g.k.nX=function(){this.Yf=Math.min(3E5,2*this.Yf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Yf+15E3*Math.random();g.Cr(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Yf=5E3};g.Ua(W7,KYa);g.k=W7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.hg=function(a){return this.B.hg(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.Z||(this.Z=!0,g.Be(this.B),OYa(this),g.Be(this.u),this.u=null,this.ma=function(){return""})};
g.k.isDisposed=function(){return this.Z};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.X="";this.u.stop();this.D=a||null;this.C=b||0;a=this.ya+"/test";b=this.ya+"/bind";var d=new O7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Pf=null);d.Pf=this;this.i=d;X7(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.vk||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.vk=f}e?(3!=e.getState()&&0==EYa(e)||e.getState(),this.i.connect(a,b,this.J,e.B,e.kt)):c?this.i.connect(a,
b,this.J,c.sessionId,c.arrayId):this.i.connect(a,b,this.J)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.kf(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):Y7(this)&&(X7(this),DYa(this.i,a))};
g.k.pK=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)DYa(this.i,a[b])}this.ea("handlerOpened")};
g.k.nK=function(a){var b=2==a&&401==this.i.wk;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.ID=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.aL=function(){var a={v:2};this.X&&(a.gsessionid=this.X);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.kf(a,this.D);return a};
g.k.oK=function(a){"S"==a[0]?this.X=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),BYa(this.i)):this.ea("handlerMessage",new MYa(a[0],a[1]))};
g.k.sB=function(a){(this.J.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.vk||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.vk=b}};
g.k.lY=function(){this.u.isActive();0==EYa(this.i)&&this.connect(this.D,this.C)};Z7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z7.prototype.D=function(a){a(Error("request timed out"))};var VYa=Date.now(),b8=null,e8=Array(50),d8=-1,f8=!1;g.Ua(g8,g.Jx);g8.prototype.Ih=function(){return this.screens};
g8.prototype.contains=function(a){return!!i7(this.screens,a)};
g8.prototype.get=function(a){return a?j7(this.screens,a):null};
g8.prototype.info=function(a){c8(this.J,a)};g.w(h8,g.Jx);g.k=h8.prototype;g.k.start=function(){!this.i&&isNaN(this.Pb)&&this.TN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Pb)||(g.Yt(this.Pb),this.Pb=NaN)};
g.k.xa=function(){this.stop();g.Jx.prototype.xa.call(this)};
g.k.TN=function(){this.Pb=NaN;this.i=g.bu($7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.Qa)(this.zR,this),onError:(0,g.Qa)(this.yR,this),onTimeout:(0,g.Qa)(this.AR,this)})};
g.k.zR=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.J;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new d7(a),b)};
g.k.yR=function(a){this.i=null;a.status&&404==a.status?this.u>=o_a.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=o_a[this.u],this.Pb=g.Wt((0,g.Qa)(this.TN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.AR=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var o_a=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(j8,g8);g.k=j8.prototype;g.k.start=function(){i8(this)&&this.ea("screenChange");!g.By("yt-remote-lounge-token-expiration")&&ZYa(this);g.Yt(this.i);this.i=g.Wt((0,g.Qa)(this.start,this),1E4)};
g.k.add=function(a,b){i8(this);WYa(this,a);k8(this,!1);this.ea("screenChange");b(a);a.token||ZYa(this)};
g.k.remove=function(a,b){var c=i8(this);YYa(this,a)&&(k8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.LB=function(a,b,c,d){var e=i8(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.xa=function(){g.Yt(this.i);j8.xe.xa.call(this)};
g.k.mT=function(a){i8(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k8(this,!b);b&&c8(this.J,"Missed "+b+" lounge tokens.")};
g.k.lT=function(a){c8(this.J,"Requesting lounge tokens failed: "+a)};g.w(m8,g.Jx);g.k=m8.prototype;g.k.start=function(){var a=parseInt(g.By("yt-remote-fast-check-period")||"0",10);(this.C=g.Ta()-144E5<a?0:a)?p8(this):(this.C=g.Ta()+3E5,g.Ay("yt-remote-fast-check-period",this.C),this.IG())};
g.k.isEmpty=function(){return g.af(this.i)};
g.k.update=function(){l8("Updating availability on schedule.");var a=this.J(),b=g.Pe(this.i,function(c,d){return c&&!!j7(a,d)},this);
o8(this,b)};
g.k.xa=function(){g.Yt(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.Jx.prototype.xa.call(this)};
g.k.IG=function(){g.Yt(this.B);this.B=NaN;this.u&&this.u.abort();var a=aZa(this);if($6(a)){var b=$7(this.D,"/pairing/get_screen_availability");this.u=a8(this.D,b,{lounge_token:g.We(a).join(",")},(0,g.Qa)(this.TW,this,a),(0,g.Qa)(this.SW,this))}else o8(this,{}),p8(this)};
g.k.TW=function(a,b){this.u=null;var c=g.We(aZa(this));if(g.pc(c,g.We(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;o8(this,c);p8(this)}else this.ye("Changing Screen set during request."),this.IG()};
g.k.SW=function(a){this.ye("Screen availability failed: "+a);this.u=null;p8(this)};
g.k.ye=function(a){c8("OnlineScreenService",a)};g.Ua(q8,g8);g.k=q8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.LB=function(a,b,c,d){this.u.contains(a)?this.u.LB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c8(this.J,a),d(Error(a)))};
g.k.Ih=function(a){return a?this.screens:g.fc(this.screens,g.aq(this.B,function(b){return!this.contains(b)},this))};
g.k.dJ=function(){return g.aq(this.Ih(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.eJ=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new h8(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Be(l);e(r8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Be(l);f(m)});
l.start();return(0,g.Qa)(l.stop,l)};
g.k.BR=function(a,b,c,d){g.bu($7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.Qa)(function(e,f){e=new d7(f.screen||{});if(!e.name||eZa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);eZa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(r8(this,e))},this),
onError:(0,g.Qa)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.Qa)(function(){d(Error("pairing request timed out."))},this)})};
g.k.xa=function(){g.Be(this.u);g.Be(this.i);q8.xe.xa.call(this)};
g.k.vT=function(){gZa(this);this.ea("screenChange");this.i.update()};
q8.prototype.dispose=q8.prototype.dispose;g.Ua(t8,g.Jx);g.k=t8.prototype;g.k.getScreen=function(){return this.C};
g.k.Bg=function(a){this.isDisposed()||(a&&(v8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){c8(this.Ba,a)};
g.k.fJ=function(){return null};
g.k.YG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.Qa)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.Qa)(function(){v8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.xa=function(){this.YG("");t8.xe.xa.call(this)};g.w(w8,t8);g.k=w8.prototype;g.k.XG=function(a){if(this.u){if(this.u==a)return;v8(this,"Overriding cast session with new session object");pZa(this);this.ya=!1;this.X="unknown";this.u.removeUpdateListener(this.ma);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.ma);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);lZa(this,"getMdxSessionStatus")};
g.k.nt=function(a){this.info("launchWithParams no-op for Cast: "+g.Ti(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.Qa)(function(){this.Bg()},this),(0,g.Qa)(function(){this.Bg(Error("Failed to stop receiver app."))},this)):this.Bg(Error("Stopping cast device without session."))};
g.k.YG=function(){};
g.k.xa=function(){this.info("disposeInternal");pZa(this);this.u&&(this.u.removeUpdateListener(this.ma),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;t8.prototype.xa.call(this)};
g.k.HX=function(a,b){if(!this.isDisposed())if(b)if(b=a7(b),g.Na(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Ti(b)),a){case "mdxSessionStatus":jZa(this,b);break;case "loungeToken":mZa(this,b);break;default:v8(this,"Unknown youtube message: "+a)}else v8(this,"Unable to parse message.");else v8(this,"No data in message.")};
g.k.nL=function(a,b,c,d){g.Yt(this.S);this.S=0;dZa(this.B,this.i.label,a,this.i.friendlyName,(0,g.Qa)(function(e){e?b(e):0<=d?(v8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.Wt((0,g.Qa)(this.nL,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.fJ=function(){return this.u};
g.k.CR=function(a){this.isDisposed()||a||(v8(this,"Cast session died."),this.Bg())};g.w(z8,t8);g.k=z8.prototype;g.k.XG=function(a){this.u=a;this.u.addUpdateListener(this.Ja)};
g.k.nt=function(a){this.Ka=a;this.Z()};
g.k.stop=function(){wZa(this);this.u?this.u.stop((0,g.Qa)(this.Bg,this,null),(0,g.Qa)(this.Bg,this,"Failed to stop DIAL device.")):this.Bg()};
g.k.xa=function(){wZa(this);this.u&&this.u.removeUpdateListener(this.Ja);this.u=null;t8.prototype.xa.call(this)};
g.k.DR=function(a){this.isDisposed()||a||(v8(this,"DIAL session died."),this.D(),this.D=g.Ja,this.Bg())};g.w(D8,t8);D8.prototype.stop=function(){this.Bg()};
D8.prototype.XG=function(){};
D8.prototype.nt=function(){g.Yt(this.u);this.u=NaN;var a=j7(this.B.Ih(),this.i.label);a?u8(this,a):this.Bg(Error("No such screen"))};
D8.prototype.xa=function(){g.Yt(this.u);this.u=NaN;t8.prototype.xa.call(this)};g.w(E8,g.Jx);g.k=E8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.X||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.J?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.Qa)(this.EW,this);c=new chrome.cast.ApiConfig(c,(0,g.Qa)(this.CN,this),e,d,a);c.customDialLaunchCallback=(0,g.Qa)(this.wV,this);
chrome.cast.initialize(c,(0,g.Qa)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),SYa(),this.u.subscribe("onlineScreenChange",(0,g.Qa)(this.mI,this)),this.B=zZa(this),chrome.cast.setCustomReceivers(this.B,g.Ja,(0,g.Qa)(function(f){this.ye("Failed to set initial custom receivers: "+g.Ti(f))},this)),this.ea("yt-remote-cast2-availability-change",G8(this)),b(!0))},this),(0,g.Qa)(function(f){this.ye("Failed to initialize API: "+g.Ti(f));
b(!1)},this))};
g.k.pY=function(a,b){F8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)F8("Unsetting old screen status: "+this.i.i.friendlyName),H8(this,null)}if(a&&b){if(!this.i){c=j7(this.u.Ih(),a);if(!c){F8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){F8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=xZa(this,c);a||(F8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ja,(0,g.Qa)(function(d){this.ye("Failed to set initial custom receivers: "+g.Ti(d))},this)));
F8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);H8(this,new D8(this.u,a),!0)}this.i.YG(b)}else F8("setConnectedScreenStatus: no screen.")};
g.k.qY=function(a){this.isDisposed()?this.ye("Setting connection data on disposed cast v2"):this.i?this.i.nt(a):this.ye("Setting connection data without a session")};
g.k.XP=function(){this.isDisposed()?this.ye("Stopping session on disposed cast v2"):this.i?(this.i.stop(),H8(this,null)):F8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.Qa)(this.CN,this),(0,g.Qa)(this.WW,this))};
g.k.xa=function(){this.u.unsubscribe("onlineScreenChange",(0,g.Qa)(this.mI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=PYa,b=g.Ia("yt.mdx.remote.debug.handlers_");g.dc(b||[],a);g.Be(this.i);g.Jx.prototype.xa.call(this)};
g.k.ye=function(a){c8("Controller",a)};
g.k.EN=function(a,b){this.i==a&&(b||H8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.zW=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)F8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{F8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H8(this,
new D8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H8(this,new z8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:H8(this,new w8(this.u,a,this.config_));break;default:this.ye("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.ye("Stopping receiver w/o session: "+a.friendlyName)}else this.ye("onReceiverAction_ called without receiver.")};
g.k.wV=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.ye("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.ye("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return F8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.ye('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H8(this,new z8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,A8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=tZa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Gt(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=uZa(b,c)):a=uZa(b,c)):a=C8(b);return a};
g.k.CN=function(a){var b=this;if(!this.isDisposed()&&!this.J){F8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)F8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),H8(this,new w8(this.u,c,this.config_),!0);else{this.ye("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=j7(this.u.Ih(),
d.label);e&&e7(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(F8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.Be(this.i),this.i=new w8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.Qa)(this.EN,this,this.i)),this.i.subscribe("sessionFailed",function(){return yZa(b,b.i)}),this.i.nt(null));
this.i.XG(a)}}};
g.k.WP=function(){return this.i?this.i.fJ():null};
g.k.WW=function(a){this.isDisposed()||(this.ye("Failed to estabilish a session: "+g.Ti(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.EW=function(a){F8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=G8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;G8(this)!=b&&this.ea("yt-remote-cast2-availability-change",G8(this))}};
g.k.mI=function(){this.isDisposed()||(this.B=zZa(this),F8("Updating custom receivers: "+g.Ti(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ja,(0,g.Qa)(function(){this.ye("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",G8(this)))};
E8.prototype.setLaunchParams=E8.prototype.qY;E8.prototype.setConnectedScreenStatus=E8.prototype.pY;E8.prototype.stopSession=E8.prototype.XP;E8.prototype.getCastSession=E8.prototype.WP;E8.prototype.requestSession=E8.prototype.requestSession;E8.prototype.init=E8.prototype.init;E8.prototype.dispose=E8.prototype.dispose;var N8=[];g.k=S8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Wk=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Jc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Vj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+U8(this):this.D};
g.k.clone=function(){return new S8(Y8(this))};g.w($8,g.Jx);g.k=$8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){b9(this)?(this.i?this.i.play(null,g.Ja,g9(this,"play")):f9(this,"play"),e9(this,1,W8(a9(this))),this.ea("remotePlayerChange")):c9(this,this.play)};
g.k.pause=function(){b9(this)?(this.i?this.i.pause(null,g.Ja,g9(this,"pause")):f9(this,"pause"),e9(this,2,W8(a9(this))),this.ea("remotePlayerChange")):c9(this,this.pause)};
g.k.seekTo=function(a){if(b9(this)){if(this.i){var b=a9(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Jc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,g9(this,"seekTo",{newTime:a}))}else f9(this,"seekTo",{newTime:a});e9(this,3,a);this.ea("remotePlayerChange")}else c9(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(b9(this)){this.i?this.i.stop(null,g.Ja,g9(this,"stopVideo")):f9(this,"stopVideo");var a=a9(this);a.index=-1;a.videoId="";T8(a);d9(this,a);this.ea("remotePlayerChange")}else c9(this,this.stop)};
g.k.setVolume=function(a,b){if(b9(this)){var c=a9(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.Qa)(function(){c8("CP","set receiver volume: "+d)},this),(0,g.Qa)(function(){this.ye("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.Qa)(function(){c8("CP","set receiver muted: "+b)},this),(0,g.Qa)(function(){this.ye("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f9(this,"setVolume",e)}c.muted=b;c.volume=a;d9(this,c)}else c9(this,g.Sa(this.setVolume,a,b))};
g.k.nI=function(a,b){if(b9(this)){var c=a9(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Ti(b.style),g.kf(a,c.trackData));f9(this,"setSubtitlesTrack",a);d9(this,c)}else c9(this,g.Sa(this.nI,a,b))};
g.k.setAudioTrack=function(a,b){b9(this)?(b=b.getLanguageInfo().getId(),f9(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=a9(this),a.audioTrackId=b,d9(this,a)):c9(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=a9(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);X8(l,a,c||0);void 0!==b&&(V8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Ti(h));f9(this,"setPlaylist",m);d||d9(this,l)};
g.k.ZA=function(a,b){if(b9(this)){if(a&&b){var c=a9(this);X8(c,a,b);d9(this,c)}f9(this,"previous")}else c9(this,g.Sa(this.ZA,a,b))};
g.k.nextVideo=function(a,b){if(b9(this)){if(a&&b){var c=a9(this);X8(c,a,b);d9(this,c)}f9(this,"next")}else c9(this,g.Sa(this.nextVideo,a,b))};
g.k.qs=function(){if(b9(this)){f9(this,"clearPlaylist");var a=a9(this);a.reset();d9(this,a);this.ea("remotePlayerChange")}else c9(this,this.qs)};
g.k.JK=function(){b9(this)?f9(this,"dismissAutoplay"):c9(this,this.JK)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.Jx.prototype.dispose.call(this)};
g.k.xa=function(){LZa(this);this.C=null;this.D.clear();Z8(this,null);g.Jx.prototype.xa.call(this)};
g.k.ZG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.xW=function(a,b){this.ea(a,b)};
g.k.hV=function(a){if(!a)this.Uw(null),Z8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=a9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c8("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d9(this,b)}};
g.k.Uw=function(a){c8("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),MZa(this),this.ea("remotePlayerChange")};
g.k.gV=function(a){a?(MZa(this),this.ea("remotePlayerChange")):this.Uw(null)};
g.k.tH=function(){f9(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.oV=function(){var a=IZa();a&&Z8(this,a)};
g.k.ye=function(a){c8("CP",a)};g.w(h9,g.Jx);g.k=h9.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.zc.listId=c);this.zc.videoId=d;this.zc.index=l||0;this.zc.state=3;V8(this.zc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";i9("Connecting with "+c+" and params: "+g.Ti(m));this.i.connect({method:c,params:g.Ti(m)},a,VXa())}else i9("Connecting without params"),this.i.connect({},a,VXa());PZa(this)};
g.k.sB=function(a){this.i.sB(a)};
g.k.dispose=function(){this.isDisposed()||(g.Ha("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),j9(this,3));g.Jx.prototype.dispose.call(this)};
g.k.xa=function(){k9(this);m9(this);l9(this);g.Yt(this.K);this.K=NaN;g.Yt(this.S);this.S=NaN;this.B=null;g.Vu(this.X);this.X.length=0;this.i.dispose();g.Jx.prototype.xa.call(this);this.C=this.J=this.u=this.zc=this.i=null};
g.k.lV=function(){var a=this;i9("Channel opened");this.ya&&(this.ya=!1,l9(this),this.ma=g.Wt(function(){i9("Timing out waiting for a screen.");a.Ds(1)},15E3));
ZXa(NYa(this.i),this.Ka)};
g.k.iV=function(){i9("Channel closed");isNaN(this.D)?o7(!0):o7();this.dispose()};
g.k.jV=function(a,b){o7();isNaN(this.cw())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),i9("Channel error: "+a+" without reconnection"),this.dispose()):(this.ya=!0,i9("Channel error: "+a+" with reconnection in "+this.cw()+" ms"),j9(this,2))};
g.k.TL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.q(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.kV=function(a){a.params?i9("Received: action="+a.action+", params="+g.Ti(a.params)):i9("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=a7(a.params.devices);this.u=g.co(a,function(c){return new c7(c)});
a=!!g.Wb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
SZa(this,a);a=this.TL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.ec(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
SZa(this,!1);break;case "remoteConnected":var b=new c7(a7(a.params.device));g.Wb(this.u,function(c){return c.equals(b)})||IXa(this.u,b);
break;case "remoteDisconnected":b=new c7(a7(a.params.device));g.ec(this.u,function(c){return c.equals(b)});
break;case "gracefulDisconnect":break;case "playlistModified":UZa(this,a,"QUEUE_MODIFIED");break;case "nowPlaying":WZa(this,a);break;case "onStateChange":VZa(this,a);break;case "onAdStateChange":XZa(this,a);break;case "onVolumeChanged":YZa(this,a);break;case "onSubtitlesTrackChanged":TZa(this,a);break;case "nowAutoplaying":ZZa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.J=a.params.videoId||null;this.ea("autoplayUpNext",this.J);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":$Za(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:i9("Unrecognized action: "+a.action)}};
g.k.fT=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.cw())?Y7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.Ds=function(a){i9("Disconnecting with "+a);g.Ha("yt.mdx.remote.remoteClient_",null,void 0);k9(this);this.ea("beforeDisconnect",a);1==a&&o7();OYa(this.i,a);this.dispose()};
g.k.dT=function(){var a=this.zc;this.B&&(a=this.zc.clone(),X8(a,this.B,a.index));return Y8(a)};
g.k.rY=function(a){var b=this,c=new S8(a);c.videoId&&c.videoId!=this.zc.videoId&&(this.B=c.videoId,g.Yt(this.K),this.K=g.Wt(function(){if(b.B){var e=b.B;b.B=null;b.zc.videoId!=e&&n9(b,"getNowPlaying")}},5E3));
var d=[];this.zc.listId==c.listId&&this.zc.videoId==c.videoId&&this.zc.index==c.index||d.push("remoteQueueChange");this.zc.playerState==c.playerState&&this.zc.volume==c.volume&&this.zc.muted==c.muted&&W8(this.zc)==W8(c)&&g.Ti(this.zc.trackData)==g.Ti(c.trackData)||d.push("remotePlayerChange");this.zc.reset(a);g.sc(d,function(e){this.ea(e)},this)};
g.k.mL=function(){var a=this.i.J.id,b=g.Wb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.cw=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.aT=function(){return this.C||"UNSUPPORTED"};
g.k.bT=function(){return this.J||""};
g.k.YP=function(){if(!isNaN(this.cw())){var a=this.i.u;g.Dr(a.i);a.start()}};
g.k.oY=function(a,b){n9(this,a,b);RZa(this)};
g.k.oI=function(){var a=g.lu("SID","")||"",b=g.lu("SAPISID","")||"",c=g.lu("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.Ec(g.eb(a),2);b=g.Ec(g.eb(b),2);c=g.Ec(g.eb(c),2);return g.Ec(g.eb(a+","+b+","+c),2)};
h9.prototype.subscribe=h9.prototype.subscribe;h9.prototype.unsubscribeByKey=h9.prototype.hg;h9.prototype.getProxyState=h9.prototype.fT;h9.prototype.disconnect=h9.prototype.Ds;h9.prototype.getPlayerContextData=h9.prototype.dT;h9.prototype.setPlayerContextData=h9.prototype.rY;h9.prototype.getOtherConnectedRemoteId=h9.prototype.mL;h9.prototype.getReconnectTimeout=h9.prototype.cw;h9.prototype.getAutoplayMode=h9.prototype.aT;h9.prototype.getAutoplayVideoId=h9.prototype.bT;h9.prototype.reconnect=h9.prototype.YP;
h9.prototype.sendMessage=h9.prototype.oY;h9.prototype.getXsrfToken=h9.prototype.oI;h9.prototype.isCapabilitySupportedOnConnectedDevices=h9.prototype.TL;g.w(o9,g8);g.k=o9.prototype;g.k.Ih=function(a){return this.Xe.$_gs(a)};
g.k.contains=function(a){return!!this.Xe.$_c(a)};
g.k.get=function(a){return this.Xe.$_g(a)};
g.k.start=function(){this.Xe.$_st()};
g.k.add=function(a,b,c){this.Xe.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Xe.$_r(a,b,c)};
g.k.LB=function(a,b,c,d){this.Xe.$_un(a,b,c,d)};
g.k.xa=function(){for(var a=0,b=this.i.length;a<b;++a)this.Xe.$_ubk(this.i[a]);this.i.length=0;this.Xe=null;g8.prototype.xa.call(this)};
g.k.ZP=function(){this.ea("screenChange")};
g.k.eW=function(){this.ea("onlineScreenChange")};
q8.prototype.$_st=q8.prototype.start;q8.prototype.$_gspc=q8.prototype.BR;q8.prototype.$_gsppc=q8.prototype.eJ;q8.prototype.$_c=q8.prototype.contains;q8.prototype.$_g=q8.prototype.get;q8.prototype.$_a=q8.prototype.add;q8.prototype.$_un=q8.prototype.LB;q8.prototype.$_r=q8.prototype.remove;q8.prototype.$_gs=q8.prototype.Ih;q8.prototype.$_gos=q8.prototype.dJ;q8.prototype.$_s=q8.prototype.subscribe;q8.prototype.$_ubk=q8.prototype.hg;var B9=null,H9=!1,p9=null,q9=null,G9=null,u9=[];g.w(I9,g.H);g.k=I9.prototype;g.k.xa=function(){g.H.prototype.xa.call(this);this.i.stop();this.B.stop();this.S.stop();this.ma();var a=this.Xb;a.unsubscribe("proxyStateChange",this.AN,this);a.unsubscribe("remotePlayerChange",this.Yw,this);a.unsubscribe("remoteQueueChange",this.LA,this);a.unsubscribe("previousNextChange",this.xN,this);a.unsubscribe("nowAutoplaying",this.rN,this);a.unsubscribe("autoplayDismissed",this.UM,this);this.Xb=this.u=null};
g.k.Ej=function(a){var b=g.Aa.apply(1,arguments);if(2!=this.Xb.B)if(J9(this)){var c=a;if(!a9(this.Xb).isAdPlaying()||"control_seek"!==c)switch(c){case "control_toggle_play_pause":a9(this.Xb).Jc()?this.Xb.pause():this.Xb.play();break;case "control_play":this.Xb.play();break;case "control_pause":this.Xb.pause();break;case "control_seek":this.K.cJ(b[0],b[1]);break;case "control_subtitles_set_track":K9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":b=
this.I.getCurrentTime();L9(this,0===b?void 0:b);break;case "control_seek":L9(this,b[0]);break;case "control_subtitles_set_track":K9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}};
g.k.eV=function(a){this.S.vR(a)};
g.k.dZ=function(a){this.Ej("control_subtitles_set_track",g.af(a)?null:a)};
g.k.TO=function(){var a=this.I.getOption("captions","track");g.af(a)||K9(this,a)};
g.k.Sb=function(a){this.u.Sb(a,this.I.getVideoData().lengthSeconds)};
g.k.PV=function(){g.af(this.C)||k_a(this,this.C);this.D=!1};
g.k.AN=function(a,b){this.B.stop();2===b&&this.OO()};
g.k.Yw=function(){if(J9(this)){this.i.stop();var a=a9(this.Xb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Bf=1;break;case 1082:case 1083:this.u.Bf=0;break;default:this.u.Bf=-1}switch(a.playerState){case 1081:case 1:this.Yb(new g.fJ(8));this.NO();break;case 1085:case 3:this.Yb(new g.fJ(9));break;case 1083:case 0:this.Yb(new g.fJ(2));this.K.stop();this.Sb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Yb(new g.fJ(4));break;case 2:this.Yb(new g.fJ(4));this.Sb(W8(a));
break;case -1:this.Yb(new g.fJ(64));break;case -1E3:this.Yb(new g.fJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a9(this.Xb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,k_a(this,a));a=a9(this.Xb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.X.isActive()||this.tP()}else j_a(this)};
g.k.xN=function(){this.I.ea("mdxpreviousnextchange")};
g.k.LA=function(){J9(this)||j_a(this)};
g.k.rN=function(a){isNaN(a)||this.I.ea("mdxnowautoplaying",a)};
g.k.UM=function(){this.I.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J9(this)&&this.Xb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a9(this.Xb).playerState?L9(this,a):b&&this.Xb.seekTo(a)};
g.k.tP=function(){var a=this;if(J9(this)){var b=a9(this.Xb);this.events.yc(this.Z);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.Z=this.events.T(this.I,"onVolumeChange",function(c){i_a(a,c)})}};
g.k.NO=function(){this.i.stop();if(!this.Xb.isDisposed()){var a=a9(this.Xb);a.Jc()&&this.Yb(new g.fJ(8));this.Sb(W8(a));this.i.start()}};
g.k.OO=function(){this.B.stop();this.i.stop();var a=this.Xb.C.getReconnectTimeout();2==this.Xb.B&&!isNaN(a)&&this.B.start()};
g.k.Yb=function(a){this.B.stop();var b=this.J;if(!g.kJ(b,a)){var c=g.T(a,2);c!==g.T(this.J,2)&&this.I.St(c);this.J=a;m_a(this.u,b,a)}};g.w(M9,g.V);M9.prototype.kd=function(){this.i.show()};
M9.prototype.Fb=function(){this.i.hide()};
M9.prototype.u=function(){b7("mdx-privacy-popup-cancel");this.Fb()};
M9.prototype.B=function(){b7("mdx-privacy-popup-confirm");this.Fb()};g.w(N9,g.V);N9.prototype.onStateChange=function(a){l_a(this,a.state)};g.w(O9,g.wP);O9.prototype.D=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.No=g.tc(a,this.i,this),g.xP(this,g.co(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Zh(a),this.enable(!0)):this.enable(!1)};
O9.prototype.i=function(a){return a.key};
O9.prototype.vj=function(a){return"cast-selector-receiver"===a?"Cast...":this.No[a].name};
O9.prototype.Gf=function(a){g.wP.prototype.Gf.call(this,a);this.I.setOption("remote","currentReceiver",this.No[a]);this.ub.Fb()};g.w(P9,g.vM);g.k=P9.prototype;
g.k.create=function(){var a=this.player.U(),b=g.gE(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};d_a(b,a);this.subscriptions.push(g.pv("yt-remote-before-disconnect",this.dV,this));this.subscriptions.push(g.pv("yt-remote-connection-change",this.FW,this));this.subscriptions.push(g.pv("yt-remote-receiver-availability-change",this.zN,
this));this.subscriptions.push(g.pv("yt-remote-auto-connect",this.DW,this));this.subscriptions.push(g.pv("yt-remote-receiver-resumed",this.BW,this));this.subscriptions.push(g.pv("mdx-privacy-popup-confirm",this.UX,this));this.subscriptions.push(g.pv("mdx-privacy-popup-cancel",this.TX,this));this.zN()};
g.k.load=function(){this.player.cancelPlayback();g.vM.prototype.load.call(this);this.gi=new I9(this,this.player,this.Xb);var a=(a=h_a())?a.currentTime:0;var b=F9()?new $8(z9(),void 0):null;0==a&&b&&(a=W8(a9(b)));0!==a&&this.Sb(a);m_a(this,this.Gd,this.Gd);this.player.vl(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.Bn=this.fl;g.Ce(this.gi,this.Xb);this.Xb=this.gi=null;g.vM.prototype.unload.call(this);this.player.vl(5);Q9(this)};
g.k.xa=function(){g.qv(this.subscriptions);g.vM.prototype.xa.call(this)};
g.k.il=function(a){var b=g.Aa.apply(1,arguments);this.loaded&&this.gi.Ej.apply(this.gi,[a].concat(g.v(b)))};
g.k.getAdState=function(){return this.Bf};
g.k.Wk=function(){return this.Xb?a9(this.Xb).Wk:!1};
g.k.hasNext=function(){return this.Xb?a9(this.Xb).hasNext:!1};
g.k.Sb=function(a,b){this.jM=a||0;this.player.ea("progresssync",a,b);this.player.Pa("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.jM};
g.k.getProgressState=function(){var a=a9(this.Xb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.U().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.lf():!a.isAdPlaying()&&this.player.lf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+U8(a):a.B,isAtLiveHead:1>=(a.u?a.i+U8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+U8(a):a.i,seekableStart:0<
a.C?a.C+U8(a):a.C}};
g.k.nextVideo=function(){this.Xb&&this.Xb.nextVideo()};
g.k.ZA=function(){this.Xb&&this.Xb.ZA()};
g.k.dV=function(a){1===a&&(this.vG=this.Xb?a9(this.Xb):null)};
g.k.FW=function(){var a=F9()?new $8(z9(),void 0):null;if(a){var b=this.Bn;this.loaded&&this.unload();this.Xb=a;this.vG=null;b.key!==this.fl.key&&(this.Bn=b,this.load())}else g.Be(this.Xb),this.Xb=null,this.loaded&&(this.unload(),(a=this.vG)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.zN=function(){var a=[this.fl],b=a.concat,c=e_a();O8()&&g.By("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.No=b.call(a,c);a=A9()||this.fl;R9(this,a);this.player.Pa("onMdxReceiversChange")};
g.k.DW=function(){var a=A9();R9(this,a)};
g.k.BW=function(){this.Bn=A9()};
g.k.UX=function(){this.jx=!0;Q9(this);H9=!1;B9&&D9(B9,1);B9=null};
g.k.TX=function(){this.jx=!1;Q9(this);R9(this,this.fl);this.Bn=this.fl;H9=!1;B9=null;this.player.playVideo()};
g.k.sf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.No;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q8():R9(this,b)),this.loaded?this.Bn:this.fl;case "quickCast":return 2===this.No.length&&"cast-selector-receiver"===this.No[1].key?(b&&Q8(),!0):!1}};
g.k.tH=function(){this.Xb.tH()};
g.k.Yi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.uM("remote",P9);})(_yt_player);
